name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # or your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install # or yarn install, pnpm install
      - run: npm run build # or yarn build, pnpm build (if applicable)
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}"
          channelId: live # or your desired channel
          projectId: your-project-id # replace with your Firebase project ID
